name: flutter_tencent_tsec_sdk
description: "腾讯云T-Sec设备安全SDK的Flutter插件，仅支持安卓和iOS（iOS未实现）"
version: 0.0.1
homepage:
  url: https://github.com/kaierwen/flutter_tencent_tsec_sdk
  repository: https://github.com/kaierwen/flutter_tencent_tsec_sdk
  documentation: https://github.com/kaierwen/flutter_tencent_tsec_sdk/blob/main/README.md

environment:
  sdk: ^3.6.0
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: github.kaierwen.flutter_tencent_tsec_sdk
        pluginClass: FlutterTencentTsecSdkPlugin
      ios:
        pluginClass: FlutterTencentTsecSdkPlugin
